<a href="https://colab.research.google.com/github/BedinEduardo/Colab_Repositories/blob/master/PyTorchDocumentation_Learning_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning With PyTorch: A 60 Minute Blits

## What is PyTorch

PyTorch is Python-based scientific computing package saving two board proposes:

* A Replacement for NumPy to use the power of GPU and other accelerators
* An automatic differentiation library that is useful to implement neural networks.


## Tensors

Tensors are a specialized data structure that very similar to arrays and matices.
In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model's parameters.

Tensors are similar to NumPy's ndarrays, except that tensors can run on GPU's or other specialized hardware to accelerate computing

In [ ]:
import torch
import numpy as np

## Tensor Initialization

In [ ]:
# Direct from data:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [ ]:
# From Numpy array:
np_array = np.array(data)
print(np_array)
x_np = torch.from_numpy(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [ ]:
# From another tensor
# The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicity overriden

x_ones = torch.ones_like(x_data)  #retains the properties do x_dta
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)  # overrides the datatype of x_data
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.0073, 0.2682],
        [0.4836, 0.6428]])


In [ ]:
# With random or constant values
# `shape` is a tuple fo tensor dimensions - determines the dimensionality of the output tensor.
shape = (2,3)
rand_tensor = torch.rand(shape)
print(rand_tensor)

ones_tensor = torch.ones(shape)
print(ones_tensor)

zeros_tensor = torch.zeros(shape)
print(zeros_tensor)

tensor([[0.7988, 0.7754, 0.1792],
        [0.9162, 0.1904, 0.0815]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Tensor Attributes

Tensors attributes describes their shape, datatype, and the device on which they are stored.

In [ ]:
tensor = torch.rand(3,4)
print(f"Shape: {tensor.shape}")
print(f"Dataytype: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape: torch.Size([3, 4])
Dataytype: torch.float32
Device tensor is stored on: cpu


## Tensors Operations

Over 100 operations, including transposing, indexing, slicing, mathematical operations, linear algerbra, random sampling, and more are comprehensively described **here**.

Eachof them can be run on GPU

In [ ]:
# Move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor moved to {tensor.device}")
else:
  tensor = tensor.to('cpu')
  print(f"Device tensor moved to {tensor.device}")

Device tensor moved to cpu


Try out some of the operations from the list. If you are familiar with the NumPy API.

In [ ]:
# Standard numpy-like indexing and slicing
tensor = torch.ones(4,4)
tensor[:,3] = 0.99
print(tensor)

tensor([[1.0000, 1.0000, 1.0000, 0.9900],
        [1.0000, 1.0000, 1.0000, 0.9900],
        [1.0000, 1.0000, 1.0000, 0.9900],
        [1.0000, 1.0000, 1.0000, 0.9900]])


**Joining tensors**: You can use `torch.cat` to concatenate a sequence of tensors along a given dimension. See also `torch.stack`-> subtle different from `torch.cat`

In [ ]:
t1 = torch.cat([tensor,tensor,tensor], dim=1)
print(t1)

tensor([[1.0000, 1.0000, 1.0000, 0.9900, 1.0000, 1.0000, 1.0000, 0.9900, 1.0000,
         1.0000, 1.0000, 0.9900],
        [1.0000, 1.0000, 1.0000, 0.9900, 1.0000, 1.0000, 1.0000, 0.9900, 1.0000,
         1.0000, 1.0000, 0.9900],
        [1.0000, 1.0000, 1.0000, 0.9900, 1.0000, 1.0000, 1.0000, 0.9900, 1.0000,
         1.0000, 1.0000, 0.9900],
        [1.0000, 1.0000, 1.0000, 0.9900, 1.0000, 1.0000, 1.0000, 0.9900, 1.0000,
         1.0000, 1.0000, 0.9900]])


In [ ]:
# Multiplying tensors
# This computes the element-wise product
print(f"tensor.mul(tensor): \n {tensor.mul(tensor)}")
print(f"\n tensor x tensor: \n {tensor*tensor}")

tensor.mul(tensor): 
 tensor([[1.0000, 1.0000, 1.0000, 0.9801],
        [1.0000, 1.0000, 1.0000, 0.9801],
        [1.0000, 1.0000, 1.0000, 0.9801],
        [1.0000, 1.0000, 1.0000, 0.9801]])

 tensor x tensor: 
 tensor([[1.0000, 1.0000, 1.0000, 0.9801],
        [1.0000, 1.0000, 1.0000, 0.9801],
        [1.0000, 1.0000, 1.0000, 0.9801],
        [1.0000, 1.0000, 1.0000, 0.9801]])


In [ ]:
# This computes the matrix multiplication between two tensors

print(f"tensor.matmul.T: \n: {tensor.matmul(tensor.T)}")
# Alternative sintax
print(f"tensor @ tensor.T \n: {tensor@tensor.T}")

tensor.matmul.T: 
: tensor([[3.9801, 3.9801, 3.9801, 3.9801],
        [3.9801, 3.9801, 3.9801, 3.9801],
        [3.9801, 3.9801, 3.9801, 3.9801],
        [3.9801, 3.9801, 3.9801, 3.9801]])
tensor @ tensor.T 
: tensor([[3.9801, 3.9801, 3.9801, 3.9801],
        [3.9801, 3.9801, 3.9801, 3.9801],
        [3.9801, 3.9801, 3.9801, 3.9801],
        [3.9801, 3.9801, 3.9801, 3.9801]])


In [ ]:
# Inplace operations
# Operations that have a _ sufix are in-place. For example: x.copy_(y), x.t_( ), will change x
print(tensor, "\n")
tensor.add_(5)
print(f"Inplaced tensor: {tensorm}")

tensor([[1.0000, 1.0000, 1.0000, 0.9900],
        [1.0000, 1.0000, 1.0000, 0.9900],
        [1.0000, 1.0000, 1.0000, 0.9900],
        [1.0000, 1.0000, 1.0000, 0.9900]]) 

Inplaced tensor: tensor([[6.0000, 6.0000, 6.0000, 5.9900],
        [6.0000, 6.0000, 6.0000, 5.9900],
        [6.0000, 6.0000, 6.0000, 5.9900],
        [6.0000, 6.0000, 6.0000, 5.9900]])


## Bridge with numpy

Tensors on the CPU and NumPy arrays can share their underlying memory access locations, and changing one will change the other.

### Tensor to Numpy array

In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"\n: {n}")

t: tensor([1., 1., 1., 1., 1.])

: [1. 1. 1. 1. 1.]


In [ ]:
# A change in tensor reflects in NumPy array
t.add_(1)
print(f"Tensor +1: \n{t}")
print(f"n: {n}")

Tensor +1: 
tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### Numpy array to Tensor

In [ ]:
n = np.ones(5)
print(n)
t=torch.from_numpy(n)
print(t)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
